"""Frozen reference text — generated by `python references.py`.

Do not edit by hand. The source of truth is the Word document under References/;
edit that and re-run the command. The text lives here rather than being parsed at
runtime because the .docx files are not deployed with the app.
"""

EMPIRIC_ABX_MD = """\
**Empiric Antibiotics on Admission**

*Escalation triggers first, then syndromes*

### PART 1 — WHEN TO BROADEN

The syndrome sets the base regimen. These decide what gets added.

#### MRSA → add vancomycin or linezolid

| **Strong** | **Supportive** |
| --- | --- |
| Known MRSA within 1 yr | Recent IV antibiotics (90d) |
| Necrotizing/cavitary pneumonia, empyema | Recent hospitalization (90d) |
| Post-influenza pneumonia | SNF / LTAC |
| Purulent or necrotizing SSTI | Injection drug use |
| Hemodialysis, hardware/prosthetics | Incarceration, contact sports |
| Septic shock with plausible staph source | High local prevalence |

#### Pseudomonas → antipseudomonal β-lactam

- Prior *Pseudomonas* isolate, any site, within 1 yr
- Structural lung disease: bronchiectasis, CF, severe COPD on chronic steroids
- Hospitalization ≥5 days, ICU stay, mechanical ventilation
- Neutropenia, transplant, significant immunosuppression
- Recent broad-spectrum IV antibiotics (90d)
- Devices: trach, chronic urinary catheter, PEG, chronic wounds, burns
- Classic niches: malignant otitis externa, hot-tub folliculitis, sneaker puncture osteo, ecthyma gangrenosum

**Active:** cefepime, ceftazidime, pip-tazo, meropenem, imipenem, aztreonam, cipro/levofloxacin, ceftolozane-tazo, ceftaz-avibactam.

**Not active:** ceftriaxone, cefotaxime, **ertapenem**, amp-sulbactam, amox-clav, cefazolin, cefoxitin, moxifloxacin.

Double gram-negative coverage is rarely justified — reserve for septic shock plus documented MDR risk, or unit resistance >10–15% to your chosen agent.

#### VRE → daptomycin or linezolid

The most over-covered organism on this list. Empiric coverage is almost never indicated in a general medical admission. Legitimate triggers:

- Known VRE colonization **plus** a plausible enterococcal source
- Liver transplant with hepatobiliary source
- Prolonged hospitalization with heavy vancomycin/cephalosporin exposure
- Neutropenic fever, known colonization, hemodynamically unstable

**Daptomycin is inactivated by surfactant — never for pneumonia.** Linezolid is bacteriostatic and generally second-line for bacteremia; serotonin syndrome risk with SSRIs.

Related gap worth holding onto: **cephalosporins have no enterococcal activity at all.** A patient on ceftriaxone with an enterococcal source is functionally untreated. Ampicillin covers susceptible *E. faecalis*; pip-tazo does too.

#### ESBL → carbapenem

- Prior ESBL isolate
- Travel to high-prevalence regions (Indian subcontinent, SE Asia, Middle East, North Africa)
- Recent β-lactam or fluoroquinolone exposure
- Recurrent UTI, chronic catheter, urologic instrumentation
- LTAC residence

**Do not use pip-tazo for ESBL bacteremia** — MERINO showed higher mortality vs meropenem. Cefepime is unreliable (inoculum effect). Ertapenem if not critically ill and no Pseudomonas concern; meropenem otherwise.

#### CRE / difficult-to-treat resistance

| **Mechanism** | **Options** |
| --- | --- |
| KPC | ceftaz-avibactam, mero-vaborbactam, imipenem-relebactam |
| Metallo-β-lactamase (NDM, VIM, IMP) | ceftaz-avibactam **+** aztreonam; cefiderocol; aztreonam-avibactam |
| OXA-48 | ceftaz-avibactam |
| DTR-*Pseudomonas* | ceftolozane-tazo, ceftaz-avibactam, imipenem-relebactam, cefiderocol |
| *Acinetobacter* | high-dose amp-sulbactam, cefiderocol, minocycline, polymyxin |
| *S. maltophilia* | TMP-SMX, minocycline, levofloxacin, cefiderocol |

#### Anaerobes

**Cover:** perforation, diverticulitis, appendicitis, cholangitis, intra-abdominal abscess; lung abscess, necrotizing pneumonia, empyema; odontogenic and deep neck infection, Ludwig angina, Lemierre; diabetic foot with necrosis or gangrene; necrotizing soft tissue infection; bites; PID, tubo-ovarian abscess, septic abortion; brain abscess; any GU tract reconstructed with bowel.

**Don't cover:**

- **Infected obstructing stone, pyelonephritis, urosepsis.** The urinary tract is not an anaerobic environment. Even emphysematous pyelonephritis — which looks like it should be clostridial — is overwhelmingly *E. coli* and *Klebsiella* fermenting glucose in diabetic tissue. Metronidazole here adds *C. diff* risk and nothing else. Exceptions: perinephric abscess with enteric fistula, urinary diversion through bowel.
- **Aspiration pneumonia.** IDSA 2019 dropped routine anaerobic coverage; this is a strep/GNR/staph disease. Cover only for demonstrated abscess, empyema, or necrotizing pneumonia.

**Active:** metronidazole, pip-tazo, all carbapenems, amp-sulbactam, amox-clav, cefoxitin/cefotetan, clindamycin, tigecycline/eravacycline, moxifloxacin (partial).

**Not active:** ceftriaxone, cefepime, ceftazidime, aztreonam, cefazolin, levo/ciprofloxacin, aminoglycosides, ceftaz-avibactam.

*B. fragilis* resistance to clindamycin is now ~30–40%, cefoxitin ~15–25%. Amp-sulbactam has ~40–50% *E. coli* resistance in many US regions.

### PART 2 — BY SYNDROME

##### Sepsis, source unknown

**Vancomycin + pip-tazo**, or **vancomycin + cefepime + metronidazole** if intra-abdominal source plausible. Meropenem if prior ESBL/MDR.

*Vanc/pip-tazo AKI:* observational signal is confounded by pip-tazo's effect on creatinine secretion. ACORN found no AKI difference vs cefepime — but more neurotoxicity with cefepime. Choose on spectrum, not on the AKI concern.

##### Community-acquired pneumonia

- Non-severe: ceftriaxone + azithromycin, or respiratory fluoroquinolone
- Severe/ICU: β-lactam + macrolide preferred over β-lactam + fluoroquinolone
- MRSA coverage: prior isolate, cavitary/necrotizing, empyema, post-influenza, gross hemoptysis, or severe disease with shock plus risk factors. Linezolid often favored for necrotizing MRSA pneumonia (ELF penetration, toxin suppression)
- Pseudomonas coverage: prior isolate, bronchiectasis/CF/severe COPD, recent hospitalization with IV antibiotics
- Oseltamivir in season

##### HAP / VAP

Pip-tazo, cefepime, or meropenem. Add vancomycin/linezolid for MRSA risk factors, unit prevalence >20% or unknown, or high mortality risk. VAP covers MRSA + Pseudomonas + other GNR. Second gram-negative agent only for septic shock, prior IV antibiotics (90d), ≥5 days hospitalized or ARDS preceding, acute RRT, or unit MDR prevalence >10%.

##### Urinary tract

- Low risk pyelonephritis: **ceftriaxone**
- Healthcare exposure, catheter, recent antibiotics, prior resistant isolate: **cefepime or pip-tazo**
- Prior ESBL: **meropenem or ertapenem**
- Urosepsis: cefepime or pip-tazo, ± vancomycin for hardware, prior MRSA, or shock
- Add **ampicillin** when enterococcus is plausible — prior instrumentation, indwelling stent, chronic catheter

**Infected obstructing stone:** a drainage problem before it is an antibiotic problem. Antibiotics do not sterilize an obstructed, high-pressure collecting system — urology or IR for nephrostomy or retrograde stent, and delay in decompression is what drives mortality. Organisms: *E. coli*, *Klebsiella*, *Proteus*, *Pseudomonas*, *Enterococcus* (especially with prior stents), *Candida*. Ceftriaxone if community-acquired and low risk; cefepime or pip-tazo if instrumented, stented, healthcare-exposed, or septic; meropenem if prior ESBL; vancomycin for shock, hardware, or prior MRSA. **No anaerobic coverage.** A struvite stone means a urease producer has been colonizing that system for a long time — *Proteus*, *Providencia*, *Morganella*, *Klebsiella*.

##### Intra-abdominal

- Community-acquired, mild-moderate: ceftriaxone + metronidazole, ertapenem, or cefoxitin
- Community-acquired, severe: pip-tazo, cefepime + metronidazole, or meropenem
- Healthcare-associated/postoperative: pip-tazo or meropenem ± vancomycin ± echinocandin
- Add enterococcal coverage: healthcare-associated, postoperative, immunosuppressed, prosthetic valve, recurrent
- Add antifungal: upper GI perforation, recurrent perforation, severe disease, immunosuppression. Echinocandin if critically ill, fluconazole if stable

**SBP:** ceftriaxone. Healthcare-associated or recent antibiotics → pip-tazo or carbapenem.

**Cholangitis:** ceftriaxone + metronidazole or pip-tazo — plus ERCP.

**Necrotizing pancreatitis:** no prophylaxis. Treat only documented infected necrosis (carbapenems penetrate best).

**C. difficile:** oral vancomycin or fidaxomicin. Fulminant → oral vancomycin + IV metronidazole, surgical consult.

##### Skin and soft tissue

- Nonpurulent cellulitis: **cefazolin or ceftriaxone** — streptococcal disease, MRSA coverage not routine
- Purulent/abscess: I&D is the treatment; TMP-SMX or doxycycline, vancomycin if systemically ill
- Severe: vancomycin + pip-tazo
- Necrotizing: vancomycin (or linezolid) + pip-tazo (or meropenem) + **clindamycin for toxin suppression**; debridement is the treatment. Consider IVIG for streptococcal TSS
- Diabetic foot, moderate-severe: amp-sulbactam, ertapenem, or pip-tazo; vancomycin for MRSA risk; Pseudomonas coverage for maceration, water exposure, prior isolate, or treatment failure
- Bites: amp-sulbactam or amox-clav (*Pasteurella*, *Eikenella*, *Capnocytophaga*). Cephalexin and clindamycin miss both *Pasteurella* and *Eikenella*
- Salt/brackish water with cirrhosis → *Vibrio vulnificus*: doxycycline + ceftriaxone. Fresh water → *Aeromonas*: cipro or ceftriaxone

##### Meningitis

Vancomycin + ceftriaxone. Add **ampicillin** for *Listeria* if >50, immunocompromised, pregnant, or alcohol use disorder. Post-neurosurgical/shunt/penetrating trauma → vancomycin + cefepime or meropenem. Add acyclovir for encephalitic features. Do not delay antibiotics for imaging or LP.

##### Endocarditis

Native valve: vancomycin ± ceftriaxone; add antipseudomonal coverage for PWID. Prosthetic valve: vancomycin + gentamicin + rifampin ± cefepime.

##### Neutropenic fever

Antipseudomonal β-lactam monotherapy — cefepime, pip-tazo, meropenem, or imipenem. Add vancomycin only for hemodynamic instability, pneumonia, suspected line infection, SSTI, known MRSA colonization, or severe mucositis on fluoroquinolone prophylaxis. Antifungal for persistent fever: echinocandin, liposomal amphotericin, or mold-active azole.

##### Bone and joint

Septic arthritis: vancomycin + ceftriaxone (cefepime for Pseudomonas risk or PWID); gonococcal → ceftriaxone. **Vertebral osteomyelitis: if hemodynamically stable, don't start empirics** — blind therapy commits the patient to six weeks and burns the diagnosis. Prosthetic joint: vancomycin + cefepime, coordinate with ortho.

##### Line infection

Vancomycin + antipseudomonal β-lactam. Add echinocandin for TPN, femoral line, prolonged broad-spectrum antibiotics, hematologic malignancy, transplant, or multi-site *Candida* colonization.

##### Asplenia

Ceftriaxone + vancomycin. Encapsulated organisms, plus *Capnocytophaga* after dog bite.

### β-LACTAM ALLERGY

\\>90% of reported penicillin allergies are not real. Cephalosporins are safe with non-severe penicillin allergy — cross-reactivity tracks R1 side chains, and cefazolin shares its side chain with nothing. Aztreonam is the option for true anaphylaxis, but shares a side chain with ceftazidime.

*Local antibiogram overrides all of the above.*\
"""
