"""Frozen reference text — generated by `python references.py`.

Do not edit by hand. The source of truth is the Word document under References/;
edit that and re-run the command. The text lives here rather than being parsed at
runtime because the .docx files are not deployed with the app.
"""

EMPIRIC_ABX_MD = """\
#### MRSA

| **Strong** | **Supportive** |
| --- | --- |
| Known MRSA within 1 yr | Recent IV antibiotics (90d) |
| Necrotizing/cavitary pneumonia, empyema | Recent hospitalization (90d) |
| Post-influenza pneumonia | SNF / LTAC |
| Purulent or necrotizing SSTI | Injection drug use |
| Hemodialysis, hardware/prosthetics | Incarceration, contact sports |
| Septic shock with plausible staph source | High local prevalence |

#### Pseudomonas

- Prior *Pseudomonas* isolate, any site, within 1 yr
- Structural lung disease: bronchiectasis, CF, severe COPD on chronic steroids
- Hospitalization ≥5 days, ICU stay, mechanical ventilation
- Neutropenia, transplant, significant immunosuppression
- Recent broad-spectrum IV antibiotics (90d)
- Devices: trach, chronic urinary catheter, PEG, chronic wounds, burns
- Classic niches: malignant otitis externa, hot-tub folliculitis, sneaker puncture osteo, ecthyma gangrenosum

#### VRE

Empiric coverage is almost never indicated. Triggers:

- Known VRE colonization **plus** a plausible enterococcal source
- Liver transplant with hepatobiliary source
- Prolonged hospitalization with heavy vancomycin/cephalosporin exposure
- Neutropenic fever, known colonization, hemodynamically unstable

**Daptomycin is inactivated by surfactant — never for pneumonia.** Linezolid is bacteriostatic and generally second-line for bacteremia; serotonin syndrome risk with SSRIs.

#### ESBL

- Prior ESBL isolate
- Travel to high-prevalence regions (Indian subcontinent, SE Asia, Middle East, North Africa)
- Recent β-lactam or fluoroquinolone exposure
- Recurrent UTI, chronic catheter, urologic instrumentation
- LTAC residence

**Do not use pip-tazo for ESBL bacteremia**. Cefepime is unreliable (inoculum effect). Ertapenem if not critically ill and no Pseudomonas concern; meropenem otherwise.

#### Anaerobes

**Cover:** perforation, diverticulitis, appendicitis, cholangitis, intra-abdominal abscess; lung abscess, necrotizing pneumonia, empyema; odontogenic and deep neck infection, Ludwig angina, Lemierre; diabetic foot with necrosis or gangrene; necrotizing soft tissue infection; bites; PID, tubo-ovarian abscess, septic abortion; brain abscess; any GU tract reconstructed with bowel.

Amp-sulbactam has ~40–50% *E. coli* resistance in many US regions.

##### Sepsis, source unknown

**Vancomycin + pip-tazo**, or **vancomycin + cefepime + metronidazole** if intra-abdominal source plausible. Meropenem if prior ESBL/MDR.

##### Community-acquired pneumonia

- Non-severe: ceftriaxone + azithromycin, or respiratory fluoroquinolone
- Severe/ICU: β-lactam + macrolide preferred over β-lactam + fluoroquinolone
- MRSA coverage: prior isolate, cavitary/necrotizing, empyema, post-influenza, gross hemoptysis, or severe disease with shock plus risk factors. Linezolid often favored for necrotizing MRSA pneumonia (ELF penetration, toxin suppression)
- Pseudomonas coverage: prior isolate, bronchiectasis/CF/severe COPD, recent hospitalization with IV antibiotics
- Oseltamivir in season

##### HAP / VAP

Pip-tazo, cefepime, or meropenem. Add vancomycin/linezolid for MRSA risk factors, unit prevalence >20% or unknown, or high mortality risk. VAP covers MRSA + Pseudomonas + other GNR. Second gram-negative agent only for septic shock, prior IV antibiotics (90d), ≥5 days hospitalized or ARDS preceding, acute RRT, or unit MDR prevalence >10%.

##### Urinary tract

- Low risk pyelonephritis: **ceftriaxone**
- Healthcare exposure, catheter, recent antibiotics, prior resistant isolate: **cefepime or pip-tazo**
- Prior ESBL: **meropenem or ertapenem**
- Urosepsis: cefepime or pip-tazo, ± vancomycin for hardware, prior MRSA, or shock
- Add **ampicillin** when enterococcus is plausible — prior instrumentation, indwelling stent, chronic catheter

**Infected obstructing stone:** Ceftriaxone if community-acquired and low risk; cefepime or pip-tazo if instrumented, stented, healthcare-exposed, or septic; meropenem if prior ESBL; vancomycin for shock, hardware, or prior MRSA. **No anaerobic coverage.** A struvite stone means a urease producer has been colonizing that system for a long time — *Proteus*, *Providencia*, *Morganella*, *Klebsiella*.

##### Intra-abdominal

- Community-acquired, mild-moderate: ceftriaxone + metronidazole, ertapenem, or cefoxitin
- Community-acquired, severe: pip-tazo, cefepime + metronidazole, or meropenem
- Healthcare-associated/postoperative: pip-tazo or meropenem ± vancomycin ± echinocandin
- Add enterococcal coverage: healthcare-associated, postoperative, immunosuppressed, prosthetic valve, recurrent
- Add antifungal: upper GI perforation, recurrent perforation, severe disease, immunosuppression. Echinocandin if critically ill, fluconazole if stable

**SBP:** ceftriaxone. Healthcare-associated or recent antibiotics → pip-tazo or carbapenem.

**Cholangitis:** ceftriaxone + metronidazole or pip-tazo — plus ERCP.

**Necrotizing pancreatitis:** no prophylaxis. Treat only documented infected necrosis (carbapenems penetrate best).

**C. difficile:** oral vancomycin or fidaxomicin. Fulminant → oral vancomycin + IV metronidazole, surgical consult.

##### Skin and soft tissue

- Nonpurulent cellulitis: **cefazolin or ceftriaxone** — streptococcal disease, MRSA coverage not routine
- Purulent/abscess: I&D is the treatment; TMP-SMX or doxycycline, vancomycin if systemically ill
- Severe: vancomycin + pip-tazo
- Necrotizing: vancomycin (or linezolid) + pip-tazo (or meropenem) + **clindamycin for toxin suppression**; debridement is the treatment. Consider IVIG for streptococcal TSS
- Diabetic foot, moderate-severe: amp-sulbactam, ertapenem, or pip-tazo; vancomycin for MRSA risk; Pseudomonas coverage for maceration, water exposure, prior isolate, or treatment failure
- Bites: amp-sulbactam or amox-clav (*Pasteurella*, *Eikenella*, *Capnocytophaga*). Cephalexin and clindamycin miss both *Pasteurella* and *Eikenella*
- Salt/brackish water with cirrhosis → *Vibrio vulnificus*: doxycycline + ceftriaxone. Fresh water → *Aeromonas*: cipro or ceftriaxone

##### Meningitis

Vancomycin + ceftriaxone. Add **ampicillin** for *Listeria* if >50, immunocompromised, pregnant, or alcohol use disorder. Post-neurosurgical/shunt/penetrating trauma → vancomycin + cefepime or meropenem. Add acyclovir for encephalitic features. Do not delay antibiotics for imaging or LP.

##### Endocarditis

Native valve: vancomycin ± ceftriaxone; add antipseudomonal coverage for PWID. Prosthetic valve: vancomycin + gentamicin + rifampin ± cefepime.

##### Neutropenic fever

Antipseudomonal β-lactam monotherapy — cefepime, pip-tazo, meropenem, or imipenem. Add vancomycin only for hemodynamic instability, pneumonia, suspected line infection, SSTI, known MRSA colonization, or severe mucositis on fluoroquinolone prophylaxis. Antifungal for persistent fever: echinocandin, liposomal amphotericin, or mold-active azole.

##### Bone and joint

Septic arthritis: vancomycin + ceftriaxone (cefepime for Pseudomonas risk or PWID); gonococcal → ceftriaxone. **Vertebral osteomyelitis: if hemodynamically stable, don't start empirics** — blind therapy commits the patient to six weeks and burns the diagnosis. Prosthetic joint: vancomycin + cefepime, coordinate with ortho.

##### Line infection

Vancomycin + antipseudomonal β-lactam. Add echinocandin for TPN, femoral line, prolonged broad-spectrum antibiotics, hematologic malignancy, transplant, or multi-site *Candida* colonization.

##### Asplenia

Ceftriaxone + vancomycin. Encapsulated organisms, plus *Capnocytophaga* after dog bite.

#### Protein binding and hypoalbuminemia

- **Ertapenem** is ~95% protein bound — the most albumin-dependent antibiotic in common use. Low albumin raises the free fraction, which expands the volume of distribution and accelerates clearance, so the once-daily dose can fall below target for much of the interval. In the hypoalbuminemic critically ill, prefer meropenem.
- **Ceftriaxone** (~85–95%) and **daptomycin** (~90%) shift the same way, and both are also once-daily — the same trap.
- Only free drug is active. A reassuring total level can sit on top of an inadequate free level; the assay usually reports total.

#### Time- versus concentration-dependent killing

- **β-lactams kill by time above MIC.** In sepsis or with high-MIC organisms, extended (3–4 h) or continuous infusion of pip-tazo, cefepime, or meropenem improves target attainment. Always give a conventional bolus first — an infusion alone takes hours to reach concentration.
- **Aminoglycosides and fluoroquinolones are concentration-dependent** (Cmax/MIC, AUC/MIC). Once-daily aminoglycoside dosing exploits that plus the post-antibiotic effect, and is less nephrotoxic than divided dosing.
- **Vancomycin is AUC-driven** — target AUC24/MIC ≥400. AUC-guided dosing replaced trough-only monitoring in the 2020 consensus guideline; troughs of 15–20 overshoot and drive nephrotoxicity.
- **Loading doses are set by volume of distribution, not clearance.** Sepsis expands the Vd of hydrophilic drugs, so load vancomycin at 20–25 mg/kg and do *not* reduce a loading dose for renal failure — reduce the maintenance dose.

#### Penetration

- **Lung:** linezolid reaches high epithelial lining fluid concentrations; vancomycin penetrates poorly, which is part of why it underperforms in MRSA pneumonia. Aminoglycosides penetrate poorly and are inactivated at the acidic pH of purulent airways — never monotherapy for pneumonia.
- **CNS:** ceftriaxone, cefepime, meropenem, linezolid, metronidazole, and TMP-SMX cross usefully. Cefazolin, ertapenem, daptomycin, and the aminoglycosides do not.
- **Urine:** nitrofurantoin and fosfomycin concentrate in bladder urine and reach nothing else — cystitis only, never pyelonephritis, prostatitis, or bacteremia. Nitrofurantoin stops achieving urinary concentrations as CrCl falls below ~30–45.
- **Moxifloxacin** is the fluoroquinolone that does *not* concentrate in urine — do not use it for UTI.
- **Abscess:** aminoglycosides are inactive in acidic, hypoxic, high-inoculum collections. Drainage is the intervention; the antibiotic is adjunctive.

#### Oral bioavailability

- Essentially complete oral absorption: **linezolid, fluoroquinolones, metronidazole, TMP-SMX, doxycycline, fluconazole**, and clindamycin (~90%). With a working gut, IV buys nothing but a line.
- **Oral vancomycin is not absorbed** — it treats C. difficile and nothing else. The converse also holds: IV vancomycin does not treat C. difficile.
- Most β-lactams have poor or erratic oral bioavailability — the main reason serious β-lactam-susceptible infections stay parenteral.

#### Dose adjustment and toxicity

- **Cefepime** accumulates in renal impairment and causes neurotoxicity — encephalopathy, myoclonus, non-convulsive status. It is frequently missed because the patient is already delirious.
- **Linezolid** needs no renal adjustment, but is bacteriostatic and generally second-line for bacteremia. It causes myelosuppression after roughly two weeks, and is a weak MAO inhibitor — serotonin syndrome with SSRIs.
- **Ceftriaxone** is largely biliary and needs no renal adjustment; it causes biliary sludging and pseudolithiasis.
- **TMP-SMX** blocks tubular creatinine secretion, so creatinine rises without any fall in GFR. It also causes real hyperkalemia — that part is not an artifact.
- **Fluoroquinolones** chelate calcium, iron, magnesium, and tube feeds — separate dosing or the drug is not absorbed.
- **Rifampin** is a potent CYP450 inducer and will lower levels of most things the patient is already taking.
- **Daptomycin** is inactivated by pulmonary surfactant — never for pneumonia, whatever the susceptibilities say.
- **Penicillin allergy:** most reported penicillin allergies are not real, and cephalosporins are safe with a non-severe history — cross-reactivity tracks R1 side chains, and cefazolin shares its side chain with nothing. Aztreonam for true anaphylaxis, though it shares a side chain with ceftazidime.

*Local antibiogram overrides all of the above.*\
"""
